'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class reports

    '''<summary>
    '''btnCust control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCust As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnOrder As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnQueries control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnQueries As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnitem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnitem As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnEmp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEmp As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''panelCust control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panelCust As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''tblCust control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblCust As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''tblCustomer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblCustomer As Global.System.Web.UI.WebControls.AccessDataSource

    '''<summary>
    '''panelorder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panelorder As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''tblOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblOrder As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''tblOrders control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblOrders As Global.System.Web.UI.WebControls.AccessDataSource

    '''<summary>
    '''panelItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panelItem As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''tblItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblItem As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''tblItems control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblItems As Global.System.Web.UI.WebControls.AccessDataSource

    '''<summary>
    '''panelEmp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panelEmp As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''tblEmp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblEmp As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''tblEmployees control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblEmployees As Global.System.Web.UI.WebControls.AccessDataSource

    '''<summary>
    '''panelQue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panelQue As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''tblQue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblQue As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''tblQueries control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblQueries As Global.System.Web.UI.WebControls.AccessDataSource
End Class
